

project_id = "kqbybkrvatvfiwhbnqna"

[functions.send-quote-notification]

[functions.blog-sitemap]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.send-lumber-quote]

[functions.resend-diagnostic]
verify_jwt = false
