// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqbybkrvatvfiwhbnqna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxYnlia3J2YXR2Zml3aGJucW5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MzQ0ODksImV4cCI6MjA2MjMxMDQ4OX0.79EPNgABkkLGZRTGS9us5rUjoAqzQHMbTDthuqSYjhI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);